version: '3'
services:
  assembly-db:
    image: mysql:8.0
    ports:
        - 3306:3306
    volumes:
        - ./db-init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: assembly
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
  assembly-service:
    build: assembly-service
    ports:
      - 8080:8080
    depends_on:
      - assembly-db